// Mocks generated by Mockito 5.4.4 from annotations
// in gsm05/test/data/repositories/device_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:gsm05/data/datasources/remote/api_service.dart' as _i3;
import 'package:gsm05/data/models/call_model.dart' as _i5;
import 'package:gsm05/data/models/device_model.dart' as _i2;
import 'package:gsm05/data/models/message_model.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDeviceModel_0 extends _i1.SmartFake implements _i2.DeviceModel {
  _FakeDeviceModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.DeviceModel>> getDevices() => (super.noSuchMethod(
        Invocation.method(
          #getDevices,
          [],
        ),
        returnValue:
            _i4.Future<List<_i2.DeviceModel>>.value(<_i2.DeviceModel>[]),
      ) as _i4.Future<List<_i2.DeviceModel>>);

  @override
  _i4.Future<_i2.DeviceModel> getDevice(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getDevice,
          [id],
        ),
        returnValue: _i4.Future<_i2.DeviceModel>.value(_FakeDeviceModel_0(
          this,
          Invocation.method(
            #getDevice,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.DeviceModel>);

  @override
  _i4.Future<List<_i5.CallModel>> getCallHistory(
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCallHistory,
          [
            limit,
            offset,
          ],
        ),
        returnValue: _i4.Future<List<_i5.CallModel>>.value(<_i5.CallModel>[]),
      ) as _i4.Future<List<_i5.CallModel>>);

  @override
  _i4.Future<void> initiateCall(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiateCall,
          [body],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> answerCall(String? id) => (super.noSuchMethod(
        Invocation.method(
          #answerCall,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> endCall(String? id) => (super.noSuchMethod(
        Invocation.method(
          #endCall,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.MessageModel>> getMessages(
    String? threadId,
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMessages,
          [
            threadId,
            limit,
            offset,
          ],
        ),
        returnValue:
            _i4.Future<List<_i6.MessageModel>>.value(<_i6.MessageModel>[]),
      ) as _i4.Future<List<_i6.MessageModel>>);

  @override
  _i4.Future<List<_i6.MessageModel>> getThreads(
    int? limit,
    int? offset,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getThreads,
          [
            limit,
            offset,
          ],
        ),
        returnValue:
            _i4.Future<List<_i6.MessageModel>>.value(<_i6.MessageModel>[]),
      ) as _i4.Future<List<_i6.MessageModel>>);

  @override
  _i4.Future<void> sendMessage(Map<String, dynamic>? body) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMessage,
          [body],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
